// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b2N1SxytDee9rZxNaRXhrA
// Component: ZsZytXO7wQ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: b2N1SxytDee9rZxNaRXhrA/projectcss
import * as sty from "./PlasmicBoton.module.css"; // plasmic-import: ZsZytXO7wQ/css

export type PlasmicBoton__VariantMembers = {};

export type PlasmicBoton__VariantsArgs = {};
type VariantPropType = keyof PlasmicBoton__VariantsArgs;
export const PlasmicBoton__VariantProps = new Array<VariantPropType>();

export type PlasmicBoton__ArgsType = {};
type ArgPropType = keyof PlasmicBoton__ArgsType;
export const PlasmicBoton__ArgProps = new Array<ArgPropType>();

export type PlasmicBoton__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBotonProps {
  className?: string;
}

function PlasmicBoton__RenderFunc(props: {
  variants: PlasmicBoton__VariantsArgs;
  args: PlasmicBoton__ArgsType;
  overrides: PlasmicBoton__OverridesType;
  dataFetches?: PlasmicBoton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBoton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBoton__VariantsArgs;
    args?: PlasmicBoton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBoton__Fetches;
  } & Omit<PlasmicBoton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBoton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBoton__ArgProps,
      internalVariantPropNames: PlasmicBoton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicBoton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBoton";
  } else {
    func.displayName = `PlasmicBoton.${nodeName}`;
  }
  return func;
}

export const PlasmicBoton = Object.assign(
  // Top-level PlasmicBoton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBoton
    internalVariantProps: PlasmicBoton__VariantProps,
    internalArgProps: PlasmicBoton__ArgProps
  }
);

export default PlasmicBoton;
/* prettier-ignore-end */
