// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b2N1SxytDee9rZxNaRXhrA
// Component: kzMiwrSNTf
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: b2N1SxytDee9rZxNaRXhrA/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: kzMiwrSNTf/css

import Layer2Icon from "./icons/PlasmicIcon__Layer2"; // plasmic-import: sulFYVmhND/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: v628lQtltdE/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: RP7Uw6dsaBm/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: aDEPzLw92u-/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: neC6Tls1_in/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: 5ZVmA4Fqsny/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: IFQA6r2zxOA/icon
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: vRwWs7zRRkJ/icon
import Vector8Icon from "./icons/PlasmicIcon__Vector8"; // plasmic-import: hr3xExKMLW2/icon
import Vector9Icon from "./icons/PlasmicIcon__Vector9"; // plasmic-import: YeeCS-WaFGL/icon
import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: JyHlNmbP0Oj/icon
import Vector11Icon from "./icons/PlasmicIcon__Vector11"; // plasmic-import: RkqceEPUEOD/icon
import Vector12Icon from "./icons/PlasmicIcon__Vector12"; // plasmic-import: UcjCV_6-1rA/icon
import Vector13Icon from "./icons/PlasmicIcon__Vector13"; // plasmic-import: 8LOdf4iVu6L/icon
import Vector14Icon from "./icons/PlasmicIcon__Vector14"; // plasmic-import: miRG5ExZtR3/icon
import Vector15Icon from "./icons/PlasmicIcon__Vector15"; // plasmic-import: 1NsaFHxmpvd/icon
import Vector16Icon from "./icons/PlasmicIcon__Vector16"; // plasmic-import: CZAVJWqfrDy/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: iR9PTxThwpt/icon
import TrueRateLogoIcon from "./icons/PlasmicIcon__TrueRateLogo"; // plasmic-import: qO9QNwdDrLk/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: oo2jrc67Ay9/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: MPuJw5lkSE0/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: DFmRY2LVHM-/icon
import FixedIncomeLogoIcon from "./icons/PlasmicIcon__FixedIncomeLogo"; // plasmic-import: P1dBiO3WvP-/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  desktop1?: p.Flex<"div">;
  rectangle36?: p.Flex<"div">;
  buttonsButtons4?: p.Flex<"div">;
  text7?: p.Flex<"div">;
  text8?: p.Flex<"div">;
  rectangle38?: p.Flex<"div">;
  rectangle39?: p.Flex<"div">;
  asset101?: p.Flex<"div">;
  group2?: p.Flex<"div">;
  rectangle37?: p.Flex<"div">;
  saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat?: p.Flex<"div">;
  buttonsButtons?: p.Flex<"div">;
  text2?: p.Flex<"div">;
  buttonsButtons2?: p.Flex<"div">;
  text3?: p.Flex<"div">;
  text4?: p.Flex<"div">;
  buttonsButtons3?: p.Flex<"div">;
  text5?: p.Flex<"div">;
  text6?: p.Flex<"div">;
  streamlineSvg?: p.Flex<"div">;
  footer?: p.Flex<"div">;
  footer2?: p.Flex<"div">;
  footer3?: p.Flex<"div">;
  copyright2021TrueRateServicesLlc?: p.Flex<"div">;
  text9?: p.Flex<"div">;
  needHelp?: p.Flex<"div">;
  component2?: p.Flex<"div">;
  rectangle54?: p.Flex<"div">;
  maskGroup?: p.Flex<"div">;
  santorini2?: p.Flex<"div">;
  santorini3?: p.Flex<"div">;
  jcPenneyBuildingPlanoTx?: p.Flex<"div">;
  _439000000?: p.Flex<"div">;
  acquisitionFinancing?: p.Flex<"div">;
  office?: p.Flex<"div">;
  component3?: p.Flex<"div">;
  rectangle55?: p.Flex<"div">;
  maskGroup2?: p.Flex<"div">;
  santorini4?: p.Flex<"div">;
  santorini5?: p.Flex<"div">;
  jcPenneyBuildingPlanoTx2?: p.Flex<"div">;
  _4390000002?: p.Flex<"div">;
  acquisitionFinancing2?: p.Flex<"div">;
  office2?: p.Flex<"div">;
  cardDeals?: p.Flex<"div">;
  rectangle56?: p.Flex<"div">;
  maskGroup3?: p.Flex<"div">;
  santorini6?: p.Flex<"div">;
  santorini7?: p.Flex<"div">;
  _4390000003?: p.Flex<"div">;
  office3?: p.Flex<"div">;
  component4?: p.Flex<"div">;
  rectangle57?: p.Flex<"div">;
  maskGroup4?: p.Flex<"div">;
  santorini8?: p.Flex<"div">;
  santorini9?: p.Flex<"div">;
  jcPenneyBuildingPlanoTx3?: p.Flex<"div">;
  _4390000004?: p.Flex<"div">;
  acquisitionFinancing3?: p.Flex<"div">;
  office4?: p.Flex<"div">;
  component8?: p.Flex<"div">;
  rectangle58?: p.Flex<"div">;
  maskGroup5?: p.Flex<"div">;
  santorini10?: p.Flex<"div">;
  santorini11?: p.Flex<"div">;
  jcPenneyBuildingPlanoTx4?: p.Flex<"div">;
  _4390000005?: p.Flex<"div">;
  acquisitionFinancing4?: p.Flex<"div">;
  office5?: p.Flex<"div">;
  component6?: p.Flex<"div">;
  rectangle59?: p.Flex<"div">;
  maskGroup6?: p.Flex<"div">;
  santorini12?: p.Flex<"div">;
  santorini13?: p.Flex<"div">;
  jcPenneyBuildingPlanoTx5?: p.Flex<"div">;
  _4390000006?: p.Flex<"div">;
  acquisitionFinancing5?: p.Flex<"div">;
  office6?: p.Flex<"div">;
  screenShot20210826At12531?: p.Flex<"div">;
  greystoneLogo?: p.Flex<"div">;
  group?: p.Flex<"div">;
  newmarkLogoBlack?: p.Flex<"div">;
  symbols?: p.Flex<"div">;
  moleculeHeaderPositive?: p.Flex<"div">;
  pgimDark?: p.Flex<"div">;
  symbols2?: p.Flex<"div">;
  desktopGlobalNavigationDarkPgim?: p.Flex<"div">;
  navigation?: p.Flex<"div">;
  siteBranding?: p.Flex<"div">;
  assetsLogosPgimDark?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  dataFetches: PlasmicHomepage__Fetches;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"desktop1"}
            data-plasmic-override={overrides.desktop1}
            className={classNames(defaultcss.all, projectcss.all, sty.desktop1)}
          >
            <div
              data-plasmic-name={"rectangle36"}
              data-plasmic-override={overrides.rectangle36}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.rectangle36
              )}
            >
              <div
                data-plasmic-name={"buttonsButtons4"}
                data-plasmic-override={overrides.buttonsButtons4}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.buttonsButtons4
                )}
              >
                <div
                  data-plasmic-name={"text7"}
                  data-plasmic-override={overrides.text7}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.text7
                  )}
                >
                  <div
                    data-plasmic-name={"text8"}
                    data-plasmic-override={overrides.text8}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text8
                    )}
                  >
                    {"Become a Lender"}
                  </div>
                </div>
              </div>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__vhkFs)}
              displayHeight={"289px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"308px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/blank_project/images/documentSvg.svg",
                fullWidth: 308,
                fullHeight: 289,
                aspectRatio: 1.065744
              }}
            />

            <div
              data-plasmic-name={"rectangle38"}
              data-plasmic-override={overrides.rectangle38}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.rectangle38
              )}
            />

            <div
              data-plasmic-name={"rectangle39"}
              data-plasmic-override={overrides.rectangle39}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.rectangle39
              )}
            />

            <div
              data-plasmic-name={"asset101"}
              data-plasmic-override={overrides.asset101}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.asset101
              )}
            >
              <Layer2Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__bt6
                )}
                role={"img"}
              />
            </div>

            {false ? (
              <div
                data-plasmic-name={"group2"}
                data-plasmic-override={overrides.group2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group2
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___75VKx
                  )}
                >
                  {"how it works"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ereaz
                  )}
                >
                  {"People"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__kcfOd
                  )}
                >
                  {"Partner With Us"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__fGccL
                  )}
                >
                  {"Insights"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___1P3F
                  )}
                >
                  {"Login"}
                </div>
              </div>
            ) : null}

            <div
              data-plasmic-name={"rectangle37"}
              data-plasmic-override={overrides.rectangle37}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.rectangle37
              )}
            />

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__isHz0
              )}
            >
              {"CLOSE MORE DEALS, FASTER"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__reFxu
              )}
            >
              {"Spend your time closing and let TrueRate source for you."}
            </div>

            <div
              data-plasmic-name={
                "saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat"
              }
              data-plasmic-override={
                overrides.saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat
              }
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat
              )}
            >
              {
                "SAVE RESOURCES\n\nTrueRate identifies and proactively reaches out to the most primed borrowers. \n\nThe borrower is guided through the input process and vetted by our underwriting team empowered by our machine learning models. \n\nThe easy-to-use interface gathers all necessary due diligence from potential borrowers and packages into a standardized format. "
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__j60A
              )}
            >
              {
                "We make it easy for you to review, analyze, and close deals that match your lending criteria."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__itcTq
              )}
            >
              {
                "TrueRate's standardized approach to collecting due diligence takes an antiquated process into the 21st century through user-friendly technology."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text___9BVfe
              )}
            >
              {"The right deals for you"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__udCe8
              )}
            >
              {
                "SPEED OF TRANSACTION\n\nTrueRate solves common frustrations experienced with the traditional sales process, including a lack of speed and efficiency.\n\nTrueRate operates on a tiered commission structure that promotes a common goal of achieving the highest price possible in the shortest amount of time"
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__authn
              )}
            >
              {"Become a lender partner with us and  get more matched deals!"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__vni7H
              )}
            >
              {"Become a lending partner with us and close more deals."}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__cgEy3
              )}
            >
              {"STREAMLINE YOUR REVIEW"}
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__lGhMg)}
              displayHeight={"243px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"538px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/blank_project/images/transaction.svg",
                fullWidth: 538,
                fullHeight: 243,
                aspectRatio: 2.213992
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__xmri)}
              displayHeight={"263px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"367px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/blank_project/images/saveResourcesSvg.svg",
                fullWidth: 367,
                fullHeight: 263,
                aspectRatio: 1.395437
              }}
            />

            <div
              data-plasmic-name={"buttonsButtons"}
              data-plasmic-override={overrides.buttonsButtons}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.buttonsButtons
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__dYrc8
                )}
              >
                <div
                  data-plasmic-name={"text2"}
                  data-plasmic-override={overrides.text2}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text2
                  )}
                >
                  {"Become a Lender"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"buttonsButtons2"}
              data-plasmic-override={overrides.buttonsButtons2}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.buttonsButtons2
              )}
            >
              <div
                data-plasmic-name={"text3"}
                data-plasmic-override={overrides.text3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.text3
                )}
              >
                <div
                  data-plasmic-name={"text4"}
                  data-plasmic-override={overrides.text4}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text4
                  )}
                >
                  {"Start Lending"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"buttonsButtons3"}
              data-plasmic-override={overrides.buttonsButtons3}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.buttonsButtons3
              )}
            >
              <div
                data-plasmic-name={"text5"}
                data-plasmic-override={overrides.text5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.text5
                )}
              >
                <div
                  data-plasmic-name={"text6"}
                  data-plasmic-override={overrides.text6}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text6
                  )}
                >
                  {"Start Lending"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"streamlineSvg"}
              data-plasmic-override={overrides.streamlineSvg}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.streamlineSvg
              )}
            >
              <VectorIcon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___7SzcJ
                )}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__hmQbV
                )}
                role={"img"}
              />

              <Vector3Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__hbhDu
                )}
                role={"img"}
              />

              <Vector4Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___0FHhb
                )}
                role={"img"}
              />

              <Vector5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__vwSzK
                )}
                role={"img"}
              />

              <Vector6Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___0K09B
                )}
                role={"img"}
              />

              <Vector7Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___1GqL9
                )}
                role={"img"}
              />

              <Vector8Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___3U0Go
                )}
                role={"img"}
              />

              <Vector9Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___5JJeu
                )}
                role={"img"}
              />

              <Vector10Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___2QFhA
                )}
                role={"img"}
              />

              <Vector11Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__a55Ih
                )}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__ct2P
                )}
                role={"img"}
              />

              <Vector12Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__o3DeE
                )}
                role={"img"}
              />

              <Vector13Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__ud2Bo
                )}
                role={"img"}
              />

              <Vector4Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__mJxXk
                )}
                role={"img"}
              />

              <Vector5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___4LXmu
                )}
                role={"img"}
              />

              <Vector14Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__ecQfg
                )}
                role={"img"}
              />

              <Vector10Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__kgb08
                )}
                role={"img"}
              />

              <Vector10Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__nr3Nw
                )}
                role={"img"}
              />

              <Vector15Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__nokig
                )}
                role={"img"}
              />

              <Vector15Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__qvifD
                )}
                role={"img"}
              />

              <Vector15Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__unynp
                )}
                role={"img"}
              />

              <Vector10Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__yklEh
                )}
                role={"img"}
              />

              <Vector15Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__mwCek
                )}
                role={"img"}
              />

              <Vector9Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__zFcqa
                )}
                role={"img"}
              />

              <Vector16Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__cLrti
                )}
                role={"img"}
              />

              <Vector16Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__uriqI
                )}
                role={"img"}
              />

              <Vector16Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__d6WvS
                )}
                role={"img"}
              />

              <Vector16Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__kUuD
                )}
                role={"img"}
              />

              <Vector16Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__rKvt
                )}
                role={"img"}
              />

              <GroupIcon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__clR3Q
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(defaultcss.all, projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"footer2"}
                data-plasmic-override={overrides.footer2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.footer2
                )}
              >
                <div
                  data-plasmic-name={"footer3"}
                  data-plasmic-override={overrides.footer3}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.footer3
                  )}
                >
                  <div
                    data-plasmic-name={"copyright2021TrueRateServicesLlc"}
                    data-plasmic-override={
                      overrides.copyright2021TrueRateServicesLlc
                    }
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.copyright2021TrueRateServicesLlc
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__uxOPg
                      )}
                    >
                      {"Copyright 2021 True Rate Services LLC"}
                    </div>
                  </div>

                  <TrueRateLogoIcon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__wo8S4
                    )}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"text9"}
                    data-plasmic-override={overrides.text9}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.text9
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text___20ID
                      )}
                    >
                      {
                        "cooper.ramsey@truerateservices.com - Direct: (914) 359-6345 | Cell: (317) 627-3829"
                      }
                    </div>

                    <div
                      data-plasmic-name={"needHelp"}
                      data-plasmic-override={overrides.needHelp}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.needHelp
                      )}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          defaultcss.__wab_text,
                          sty.text__w7Eth
                        )}
                      >
                        {"Need help?"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text___5AAit
              )}
            >
              {"CLOSED"}
            </div>

            <div
              data-plasmic-name={"component2"}
              data-plasmic-override={overrides.component2}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.component2
              )}
            >
              <div
                data-plasmic-name={"rectangle54"}
                data-plasmic-override={overrides.rectangle54}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle54
                )}
              />

              <div
                data-plasmic-name={"maskGroup"}
                data-plasmic-override={overrides.maskGroup}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.maskGroup
                )}
              >
                <div
                  data-plasmic-name={"santorini2"}
                  data-plasmic-override={overrides.santorini2}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.santorini2
                  )}
                />
              </div>

              <div
                data-plasmic-name={"santorini3"}
                data-plasmic-override={overrides.santorini3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.santorini3
                )}
              />

              <div
                data-plasmic-name={"jcPenneyBuildingPlanoTx"}
                data-plasmic-override={overrides.jcPenneyBuildingPlanoTx}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.jcPenneyBuildingPlanoTx
                )}
              >
                {"18 Park\nJersey City, NJ"}
              </div>

              <div
                data-plasmic-name={"_439000000"}
                data-plasmic-override={overrides._439000000}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty._439000000
                )}
              >
                {"$75,000,000"}
              </div>

              <div
                data-plasmic-name={"acquisitionFinancing"}
                data-plasmic-override={overrides.acquisitionFinancing}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.acquisitionFinancing
                )}
              >
                {"Refinancing"}
              </div>

              <div
                data-plasmic-name={"office"}
                data-plasmic-override={overrides.office}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.office
                )}
              >
                {"Multifamily "}
              </div>

              <Line5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__aDqfE
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"component3"}
              data-plasmic-override={overrides.component3}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.component3
              )}
            >
              <div
                data-plasmic-name={"rectangle55"}
                data-plasmic-override={overrides.rectangle55}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle55
                )}
              />

              <div
                data-plasmic-name={"maskGroup2"}
                data-plasmic-override={overrides.maskGroup2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.maskGroup2
                )}
              >
                <div
                  data-plasmic-name={"santorini4"}
                  data-plasmic-override={overrides.santorini4}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.santorini4
                  )}
                />
              </div>

              <div
                data-plasmic-name={"santorini5"}
                data-plasmic-override={overrides.santorini5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.santorini5
                )}
              />

              <div
                data-plasmic-name={"jcPenneyBuildingPlanoTx2"}
                data-plasmic-override={overrides.jcPenneyBuildingPlanoTx2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.jcPenneyBuildingPlanoTx2
                )}
              >
                {"Isle de Sol/Simpson Bay\nSt. Maarten"}
              </div>

              <div
                data-plasmic-name={"_4390000002"}
                data-plasmic-override={overrides._4390000002}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty._4390000002
                )}
              >
                {"$18,484,000 "}
              </div>

              <div
                data-plasmic-name={"acquisitionFinancing2"}
                data-plasmic-override={overrides.acquisitionFinancing2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.acquisitionFinancing2
                )}
              >
                {"Refinancing"}
              </div>

              <div
                data-plasmic-name={"office2"}
                data-plasmic-override={overrides.office2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.office2
                )}
              >
                {"Marinas "}
              </div>

              <Line5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__zzR3I
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"cardDeals"}
              data-plasmic-override={overrides.cardDeals}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.cardDeals
              )}
            >
              <div
                data-plasmic-name={"rectangle56"}
                data-plasmic-override={overrides.rectangle56}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle56
                )}
              />

              <div
                data-plasmic-name={"maskGroup3"}
                data-plasmic-override={overrides.maskGroup3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.maskGroup3
                )}
              >
                <div
                  data-plasmic-name={"santorini6"}
                  data-plasmic-override={overrides.santorini6}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.santorini6
                  )}
                />
              </div>

              <div
                data-plasmic-name={"santorini7"}
                data-plasmic-override={overrides.santorini7}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.santorini7
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___9Z13K
                )}
              >
                {"JC Penney Building\nPlano, TX"}
              </div>

              <div
                data-plasmic-name={"_4390000003"}
                data-plasmic-override={overrides._4390000003}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty._4390000003
                )}
              >
                {"$439,000,000 "}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__xkHlh
                )}
              >
                {"Acquisition Financing"}
              </div>

              <div
                data-plasmic-name={"office3"}
                data-plasmic-override={overrides.office3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.office3
                )}
              >
                {"Office "}
              </div>

              <Line5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__cd5Em
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"component4"}
              data-plasmic-override={overrides.component4}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.component4
              )}
            >
              <div
                data-plasmic-name={"rectangle57"}
                data-plasmic-override={overrides.rectangle57}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle57
                )}
              />

              <div
                data-plasmic-name={"maskGroup4"}
                data-plasmic-override={overrides.maskGroup4}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.maskGroup4
                )}
              >
                <div
                  data-plasmic-name={"santorini8"}
                  data-plasmic-override={overrides.santorini8}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.santorini8
                  )}
                />
              </div>

              <div
                data-plasmic-name={"santorini9"}
                data-plasmic-override={overrides.santorini9}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.santorini9
                )}
              />

              <div
                data-plasmic-name={"jcPenneyBuildingPlanoTx3"}
                data-plasmic-override={overrides.jcPenneyBuildingPlanoTx3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.jcPenneyBuildingPlanoTx3
                )}
              >
                {"Bardmoor Palms\nLargo, FL"}
              </div>

              <div
                data-plasmic-name={"_4390000004"}
                data-plasmic-override={overrides._4390000004}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty._4390000004
                )}
              >
                {"$55,500,000 "}
              </div>

              <div
                data-plasmic-name={"acquisitionFinancing3"}
                data-plasmic-override={overrides.acquisitionFinancing3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.acquisitionFinancing3
                )}
              >
                {"Refinancing"}
              </div>

              <div
                data-plasmic-name={"office4"}
                data-plasmic-override={overrides.office4}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.office4
                )}
              >
                {"Office / Industrial"}
              </div>

              <Line5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__fLlQ
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"component8"}
              data-plasmic-override={overrides.component8}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.component8
              )}
            >
              <div
                data-plasmic-name={"rectangle58"}
                data-plasmic-override={overrides.rectangle58}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle58
                )}
              />

              <div
                data-plasmic-name={"maskGroup5"}
                data-plasmic-override={overrides.maskGroup5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.maskGroup5
                )}
              >
                <div
                  data-plasmic-name={"santorini10"}
                  data-plasmic-override={overrides.santorini10}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.santorini10
                  )}
                />
              </div>

              <div
                data-plasmic-name={"santorini11"}
                data-plasmic-override={overrides.santorini11}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.santorini11
                )}
              />

              <div
                data-plasmic-name={"jcPenneyBuildingPlanoTx4"}
                data-plasmic-override={overrides.jcPenneyBuildingPlanoTx4}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.jcPenneyBuildingPlanoTx4
                )}
              >
                {"560 Ninth Street\nNaples, FL"}
              </div>

              <div
                data-plasmic-name={"_4390000005"}
                data-plasmic-override={overrides._4390000005}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty._4390000005
                )}
              >
                {"$11,500,000 "}
              </div>

              <div
                data-plasmic-name={"acquisitionFinancing4"}
                data-plasmic-override={overrides.acquisitionFinancing4}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.acquisitionFinancing4
                )}
              >
                {"Construction Financing"}
              </div>

              <div
                data-plasmic-name={"office5"}
                data-plasmic-override={overrides.office5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.office5
                )}
              >
                {"Condo / Retail "}
              </div>

              <Line5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__otIo
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"component6"}
              data-plasmic-override={overrides.component6}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.component6
              )}
            >
              <div
                data-plasmic-name={"rectangle59"}
                data-plasmic-override={overrides.rectangle59}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle59
                )}
              />

              <div
                data-plasmic-name={"maskGroup6"}
                data-plasmic-override={overrides.maskGroup6}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.maskGroup6
                )}
              >
                <div
                  data-plasmic-name={"santorini12"}
                  data-plasmic-override={overrides.santorini12}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.santorini12
                  )}
                />
              </div>

              <div
                data-plasmic-name={"santorini13"}
                data-plasmic-override={overrides.santorini13}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.santorini13
                )}
              />

              <div
                data-plasmic-name={"jcPenneyBuildingPlanoTx5"}
                data-plasmic-override={overrides.jcPenneyBuildingPlanoTx5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.jcPenneyBuildingPlanoTx5
                )}
              >
                {"Crowne Plaza\nLake Buena Vista, FL"}
              </div>

              <div
                data-plasmic-name={"_4390000006"}
                data-plasmic-override={overrides._4390000006}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty._4390000006
                )}
              >
                {"$21,540,000 "}
              </div>

              <div
                data-plasmic-name={"acquisitionFinancing5"}
                data-plasmic-override={overrides.acquisitionFinancing5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.acquisitionFinancing5
                )}
              >
                {"Refinancing"}
              </div>

              <div
                data-plasmic-name={"office6"}
                data-plasmic-override={overrides.office6}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.office6
                )}
              >
                {"Hotel "}
              </div>

              <Line5Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__taual
                )}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"screenShot20210826At12531"}
              data-plasmic-override={overrides.screenShot20210826At12531}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.screenShot20210826At12531
              )}
            />

            <div
              data-plasmic-name={"greystoneLogo"}
              data-plasmic-override={overrides.greystoneLogo}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.greystoneLogo
              )}
            >
              <div
                data-plasmic-name={"group"}
                data-plasmic-override={overrides.group}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group
                )}
              >
                <Group2Icon
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.svg__lkhse
                  )}
                  role={"img"}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"newmarkLogoBlack"}
              data-plasmic-override={overrides.newmarkLogoBlack}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.newmarkLogoBlack
              )}
            >
              <div
                data-plasmic-name={"symbols"}
                data-plasmic-override={overrides.symbols}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.symbols
                )}
              >
                <div
                  data-plasmic-name={"moleculeHeaderPositive"}
                  data-plasmic-override={overrides.moleculeHeaderPositive}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.moleculeHeaderPositive
                  )}
                >
                  <Group3Icon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__fnOar
                    )}
                    role={"img"}
                  />
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"pgimDark"}
              data-plasmic-override={overrides.pgimDark}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.pgimDark
              )}
            >
              <div
                data-plasmic-name={"symbols2"}
                data-plasmic-override={overrides.symbols2}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.symbols2
                )}
              >
                <div
                  data-plasmic-name={"desktopGlobalNavigationDarkPgim"}
                  data-plasmic-override={
                    overrides.desktopGlobalNavigationDarkPgim
                  }
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.desktopGlobalNavigationDarkPgim
                  )}
                >
                  <div
                    data-plasmic-name={"navigation"}
                    data-plasmic-override={overrides.navigation}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.navigation
                    )}
                  >
                    <div
                      data-plasmic-name={"siteBranding"}
                      data-plasmic-override={overrides.siteBranding}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.siteBranding
                      )}
                    >
                      <div
                        data-plasmic-name={"assetsLogosPgimDark"}
                        data-plasmic-override={overrides.assetsLogosPgimDark}
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.assetsLogosPgimDark
                        )}
                      >
                        <FixedIncomeLogoIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__jifGy
                          )}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__xgihT)}
              displayHeight={"13px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"230px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/blank_project/images/wdLogo.svg",
                fullWidth: 230,
                fullHeight: 13,
                aspectRatio: 17.692308
              }}
            />
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "desktop1",
    "rectangle36",
    "buttonsButtons4",
    "text7",
    "text8",
    "rectangle38",
    "rectangle39",
    "asset101",
    "group2",
    "rectangle37",
    "saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat",
    "buttonsButtons",
    "text2",
    "buttonsButtons2",
    "text3",
    "text4",
    "buttonsButtons3",
    "text5",
    "text6",
    "streamlineSvg",
    "footer",
    "footer2",
    "footer3",
    "copyright2021TrueRateServicesLlc",
    "text9",
    "needHelp",
    "component2",
    "rectangle54",
    "maskGroup",
    "santorini2",
    "santorini3",
    "jcPenneyBuildingPlanoTx",
    "_439000000",
    "acquisitionFinancing",
    "office",
    "component3",
    "rectangle55",
    "maskGroup2",
    "santorini4",
    "santorini5",
    "jcPenneyBuildingPlanoTx2",
    "_4390000002",
    "acquisitionFinancing2",
    "office2",
    "cardDeals",
    "rectangle56",
    "maskGroup3",
    "santorini6",
    "santorini7",
    "_4390000003",
    "office3",
    "component4",
    "rectangle57",
    "maskGroup4",
    "santorini8",
    "santorini9",
    "jcPenneyBuildingPlanoTx3",
    "_4390000004",
    "acquisitionFinancing3",
    "office4",
    "component8",
    "rectangle58",
    "maskGroup5",
    "santorini10",
    "santorini11",
    "jcPenneyBuildingPlanoTx4",
    "_4390000005",
    "acquisitionFinancing4",
    "office5",
    "component6",
    "rectangle59",
    "maskGroup6",
    "santorini12",
    "santorini13",
    "jcPenneyBuildingPlanoTx5",
    "_4390000006",
    "acquisitionFinancing5",
    "office6",
    "screenShot20210826At12531",
    "greystoneLogo",
    "group",
    "newmarkLogoBlack",
    "symbols",
    "moleculeHeaderPositive",
    "pgimDark",
    "symbols2",
    "desktopGlobalNavigationDarkPgim",
    "navigation",
    "siteBranding",
    "assetsLogosPgimDark"
  ],
  desktop1: [
    "desktop1",
    "rectangle36",
    "buttonsButtons4",
    "text7",
    "text8",
    "rectangle38",
    "rectangle39",
    "asset101",
    "group2",
    "rectangle37",
    "saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat",
    "buttonsButtons",
    "text2",
    "buttonsButtons2",
    "text3",
    "text4",
    "buttonsButtons3",
    "text5",
    "text6",
    "streamlineSvg",
    "footer",
    "footer2",
    "footer3",
    "copyright2021TrueRateServicesLlc",
    "text9",
    "needHelp",
    "component2",
    "rectangle54",
    "maskGroup",
    "santorini2",
    "santorini3",
    "jcPenneyBuildingPlanoTx",
    "_439000000",
    "acquisitionFinancing",
    "office",
    "component3",
    "rectangle55",
    "maskGroup2",
    "santorini4",
    "santorini5",
    "jcPenneyBuildingPlanoTx2",
    "_4390000002",
    "acquisitionFinancing2",
    "office2",
    "cardDeals",
    "rectangle56",
    "maskGroup3",
    "santorini6",
    "santorini7",
    "_4390000003",
    "office3",
    "component4",
    "rectangle57",
    "maskGroup4",
    "santorini8",
    "santorini9",
    "jcPenneyBuildingPlanoTx3",
    "_4390000004",
    "acquisitionFinancing3",
    "office4",
    "component8",
    "rectangle58",
    "maskGroup5",
    "santorini10",
    "santorini11",
    "jcPenneyBuildingPlanoTx4",
    "_4390000005",
    "acquisitionFinancing4",
    "office5",
    "component6",
    "rectangle59",
    "maskGroup6",
    "santorini12",
    "santorini13",
    "jcPenneyBuildingPlanoTx5",
    "_4390000006",
    "acquisitionFinancing5",
    "office6",
    "screenShot20210826At12531",
    "greystoneLogo",
    "group",
    "newmarkLogoBlack",
    "symbols",
    "moleculeHeaderPositive",
    "pgimDark",
    "symbols2",
    "desktopGlobalNavigationDarkPgim",
    "navigation",
    "siteBranding",
    "assetsLogosPgimDark"
  ],
  rectangle36: ["rectangle36", "buttonsButtons4", "text7", "text8"],
  buttonsButtons4: ["buttonsButtons4", "text7", "text8"],
  text7: ["text7", "text8"],
  text8: ["text8"],
  rectangle38: ["rectangle38"],
  rectangle39: ["rectangle39"],
  asset101: ["asset101"],
  group2: ["group2"],
  rectangle37: ["rectangle37"],
  saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat:
    [
      "saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat"
    ],
  buttonsButtons: ["buttonsButtons", "text2"],
  text2: ["text2"],
  buttonsButtons2: ["buttonsButtons2", "text3", "text4"],
  text3: ["text3", "text4"],
  text4: ["text4"],
  buttonsButtons3: ["buttonsButtons3", "text5", "text6"],
  text5: ["text5", "text6"],
  text6: ["text6"],
  streamlineSvg: ["streamlineSvg"],
  footer: [
    "footer",
    "footer2",
    "footer3",
    "copyright2021TrueRateServicesLlc",
    "text9",
    "needHelp"
  ],
  footer2: [
    "footer2",
    "footer3",
    "copyright2021TrueRateServicesLlc",
    "text9",
    "needHelp"
  ],
  footer3: ["footer3", "copyright2021TrueRateServicesLlc", "text9", "needHelp"],
  copyright2021TrueRateServicesLlc: ["copyright2021TrueRateServicesLlc"],
  text9: ["text9", "needHelp"],
  needHelp: ["needHelp"],
  component2: [
    "component2",
    "rectangle54",
    "maskGroup",
    "santorini2",
    "santorini3",
    "jcPenneyBuildingPlanoTx",
    "_439000000",
    "acquisitionFinancing",
    "office"
  ],
  rectangle54: ["rectangle54"],
  maskGroup: ["maskGroup", "santorini2"],
  santorini2: ["santorini2"],
  santorini3: ["santorini3"],
  jcPenneyBuildingPlanoTx: ["jcPenneyBuildingPlanoTx"],
  _439000000: ["_439000000"],
  acquisitionFinancing: ["acquisitionFinancing"],
  office: ["office"],
  component3: [
    "component3",
    "rectangle55",
    "maskGroup2",
    "santorini4",
    "santorini5",
    "jcPenneyBuildingPlanoTx2",
    "_4390000002",
    "acquisitionFinancing2",
    "office2"
  ],
  rectangle55: ["rectangle55"],
  maskGroup2: ["maskGroup2", "santorini4"],
  santorini4: ["santorini4"],
  santorini5: ["santorini5"],
  jcPenneyBuildingPlanoTx2: ["jcPenneyBuildingPlanoTx2"],
  _4390000002: ["_4390000002"],
  acquisitionFinancing2: ["acquisitionFinancing2"],
  office2: ["office2"],
  cardDeals: [
    "cardDeals",
    "rectangle56",
    "maskGroup3",
    "santorini6",
    "santorini7",
    "_4390000003",
    "office3"
  ],
  rectangle56: ["rectangle56"],
  maskGroup3: ["maskGroup3", "santorini6"],
  santorini6: ["santorini6"],
  santorini7: ["santorini7"],
  _4390000003: ["_4390000003"],
  office3: ["office3"],
  component4: [
    "component4",
    "rectangle57",
    "maskGroup4",
    "santorini8",
    "santorini9",
    "jcPenneyBuildingPlanoTx3",
    "_4390000004",
    "acquisitionFinancing3",
    "office4"
  ],
  rectangle57: ["rectangle57"],
  maskGroup4: ["maskGroup4", "santorini8"],
  santorini8: ["santorini8"],
  santorini9: ["santorini9"],
  jcPenneyBuildingPlanoTx3: ["jcPenneyBuildingPlanoTx3"],
  _4390000004: ["_4390000004"],
  acquisitionFinancing3: ["acquisitionFinancing3"],
  office4: ["office4"],
  component8: [
    "component8",
    "rectangle58",
    "maskGroup5",
    "santorini10",
    "santorini11",
    "jcPenneyBuildingPlanoTx4",
    "_4390000005",
    "acquisitionFinancing4",
    "office5"
  ],
  rectangle58: ["rectangle58"],
  maskGroup5: ["maskGroup5", "santorini10"],
  santorini10: ["santorini10"],
  santorini11: ["santorini11"],
  jcPenneyBuildingPlanoTx4: ["jcPenneyBuildingPlanoTx4"],
  _4390000005: ["_4390000005"],
  acquisitionFinancing4: ["acquisitionFinancing4"],
  office5: ["office5"],
  component6: [
    "component6",
    "rectangle59",
    "maskGroup6",
    "santorini12",
    "santorini13",
    "jcPenneyBuildingPlanoTx5",
    "_4390000006",
    "acquisitionFinancing5",
    "office6"
  ],
  rectangle59: ["rectangle59"],
  maskGroup6: ["maskGroup6", "santorini12"],
  santorini12: ["santorini12"],
  santorini13: ["santorini13"],
  jcPenneyBuildingPlanoTx5: ["jcPenneyBuildingPlanoTx5"],
  _4390000006: ["_4390000006"],
  acquisitionFinancing5: ["acquisitionFinancing5"],
  office6: ["office6"],
  screenShot20210826At12531: ["screenShot20210826At12531"],
  greystoneLogo: ["greystoneLogo", "group"],
  group: ["group"],
  newmarkLogoBlack: ["newmarkLogoBlack", "symbols", "moleculeHeaderPositive"],
  symbols: ["symbols", "moleculeHeaderPositive"],
  moleculeHeaderPositive: ["moleculeHeaderPositive"],
  pgimDark: [
    "pgimDark",
    "symbols2",
    "desktopGlobalNavigationDarkPgim",
    "navigation",
    "siteBranding",
    "assetsLogosPgimDark"
  ],
  symbols2: [
    "symbols2",
    "desktopGlobalNavigationDarkPgim",
    "navigation",
    "siteBranding",
    "assetsLogosPgimDark"
  ],
  desktopGlobalNavigationDarkPgim: [
    "desktopGlobalNavigationDarkPgim",
    "navigation",
    "siteBranding",
    "assetsLogosPgimDark"
  ],
  navigation: ["navigation", "siteBranding", "assetsLogosPgimDark"],
  siteBranding: ["siteBranding", "assetsLogosPgimDark"],
  assetsLogosPgimDark: ["assetsLogosPgimDark"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  desktop1: "div";
  rectangle36: "div";
  buttonsButtons4: "div";
  text7: "div";
  text8: "div";
  rectangle38: "div";
  rectangle39: "div";
  asset101: "div";
  group2: "div";
  rectangle37: "div";
  saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat: "div";
  buttonsButtons: "div";
  text2: "div";
  buttonsButtons2: "div";
  text3: "div";
  text4: "div";
  buttonsButtons3: "div";
  text5: "div";
  text6: "div";
  streamlineSvg: "div";
  footer: "div";
  footer2: "div";
  footer3: "div";
  copyright2021TrueRateServicesLlc: "div";
  text9: "div";
  needHelp: "div";
  component2: "div";
  rectangle54: "div";
  maskGroup: "div";
  santorini2: "div";
  santorini3: "div";
  jcPenneyBuildingPlanoTx: "div";
  _439000000: "div";
  acquisitionFinancing: "div";
  office: "div";
  component3: "div";
  rectangle55: "div";
  maskGroup2: "div";
  santorini4: "div";
  santorini5: "div";
  jcPenneyBuildingPlanoTx2: "div";
  _4390000002: "div";
  acquisitionFinancing2: "div";
  office2: "div";
  cardDeals: "div";
  rectangle56: "div";
  maskGroup3: "div";
  santorini6: "div";
  santorini7: "div";
  _4390000003: "div";
  office3: "div";
  component4: "div";
  rectangle57: "div";
  maskGroup4: "div";
  santorini8: "div";
  santorini9: "div";
  jcPenneyBuildingPlanoTx3: "div";
  _4390000004: "div";
  acquisitionFinancing3: "div";
  office4: "div";
  component8: "div";
  rectangle58: "div";
  maskGroup5: "div";
  santorini10: "div";
  santorini11: "div";
  jcPenneyBuildingPlanoTx4: "div";
  _4390000005: "div";
  acquisitionFinancing4: "div";
  office5: "div";
  component6: "div";
  rectangle59: "div";
  maskGroup6: "div";
  santorini12: "div";
  santorini13: "div";
  jcPenneyBuildingPlanoTx5: "div";
  _4390000006: "div";
  acquisitionFinancing5: "div";
  office6: "div";
  screenShot20210826At12531: "div";
  greystoneLogo: "div";
  group: "div";
  newmarkLogoBlack: "div";
  symbols: "div";
  moleculeHeaderPositive: "div";
  pgimDark: "div";
  symbols2: "div";
  desktopGlobalNavigationDarkPgim: "div";
  navigation: "div";
  siteBranding: "div";
  assetsLogosPgimDark: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    desktop1: makeNodeComponent("desktop1"),
    rectangle36: makeNodeComponent("rectangle36"),
    buttonsButtons4: makeNodeComponent("buttonsButtons4"),
    text7: makeNodeComponent("text7"),
    text8: makeNodeComponent("text8"),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle39: makeNodeComponent("rectangle39"),
    asset101: makeNodeComponent("asset101"),
    group2: makeNodeComponent("group2"),
    rectangle37: makeNodeComponent("rectangle37"),
    saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat:
      makeNodeComponent(
        "saveResourcesTrueRateIdentifiesAndProactivelyReachesOutToTheMostPrimedBorrowersTheBorrowerIsGuidedThroughTheInputProcessAndVettedByOurUnderwritingTeamEmpoweredByOurMachineLearningModelsTheEasyToUseInterfaceGathersAllNecessaryDueDiligenceFromPotentialBorrowersAndPackagesIntoAStandardizedFormat"
      ),
    buttonsButtons: makeNodeComponent("buttonsButtons"),
    text2: makeNodeComponent("text2"),
    buttonsButtons2: makeNodeComponent("buttonsButtons2"),
    text3: makeNodeComponent("text3"),
    text4: makeNodeComponent("text4"),
    buttonsButtons3: makeNodeComponent("buttonsButtons3"),
    text5: makeNodeComponent("text5"),
    text6: makeNodeComponent("text6"),
    streamlineSvg: makeNodeComponent("streamlineSvg"),
    footer: makeNodeComponent("footer"),
    footer2: makeNodeComponent("footer2"),
    footer3: makeNodeComponent("footer3"),
    copyright2021TrueRateServicesLlc: makeNodeComponent(
      "copyright2021TrueRateServicesLlc"
    ),
    text9: makeNodeComponent("text9"),
    needHelp: makeNodeComponent("needHelp"),
    component2: makeNodeComponent("component2"),
    rectangle54: makeNodeComponent("rectangle54"),
    maskGroup: makeNodeComponent("maskGroup"),
    santorini2: makeNodeComponent("santorini2"),
    santorini3: makeNodeComponent("santorini3"),
    jcPenneyBuildingPlanoTx: makeNodeComponent("jcPenneyBuildingPlanoTx"),
    _439000000: makeNodeComponent("_439000000"),
    acquisitionFinancing: makeNodeComponent("acquisitionFinancing"),
    office: makeNodeComponent("office"),
    component3: makeNodeComponent("component3"),
    rectangle55: makeNodeComponent("rectangle55"),
    maskGroup2: makeNodeComponent("maskGroup2"),
    santorini4: makeNodeComponent("santorini4"),
    santorini5: makeNodeComponent("santorini5"),
    jcPenneyBuildingPlanoTx2: makeNodeComponent("jcPenneyBuildingPlanoTx2"),
    _4390000002: makeNodeComponent("_4390000002"),
    acquisitionFinancing2: makeNodeComponent("acquisitionFinancing2"),
    office2: makeNodeComponent("office2"),
    cardDeals: makeNodeComponent("cardDeals"),
    rectangle56: makeNodeComponent("rectangle56"),
    maskGroup3: makeNodeComponent("maskGroup3"),
    santorini6: makeNodeComponent("santorini6"),
    santorini7: makeNodeComponent("santorini7"),
    _4390000003: makeNodeComponent("_4390000003"),
    office3: makeNodeComponent("office3"),
    component4: makeNodeComponent("component4"),
    rectangle57: makeNodeComponent("rectangle57"),
    maskGroup4: makeNodeComponent("maskGroup4"),
    santorini8: makeNodeComponent("santorini8"),
    santorini9: makeNodeComponent("santorini9"),
    jcPenneyBuildingPlanoTx3: makeNodeComponent("jcPenneyBuildingPlanoTx3"),
    _4390000004: makeNodeComponent("_4390000004"),
    acquisitionFinancing3: makeNodeComponent("acquisitionFinancing3"),
    office4: makeNodeComponent("office4"),
    component8: makeNodeComponent("component8"),
    rectangle58: makeNodeComponent("rectangle58"),
    maskGroup5: makeNodeComponent("maskGroup5"),
    santorini10: makeNodeComponent("santorini10"),
    santorini11: makeNodeComponent("santorini11"),
    jcPenneyBuildingPlanoTx4: makeNodeComponent("jcPenneyBuildingPlanoTx4"),
    _4390000005: makeNodeComponent("_4390000005"),
    acquisitionFinancing4: makeNodeComponent("acquisitionFinancing4"),
    office5: makeNodeComponent("office5"),
    component6: makeNodeComponent("component6"),
    rectangle59: makeNodeComponent("rectangle59"),
    maskGroup6: makeNodeComponent("maskGroup6"),
    santorini12: makeNodeComponent("santorini12"),
    santorini13: makeNodeComponent("santorini13"),
    jcPenneyBuildingPlanoTx5: makeNodeComponent("jcPenneyBuildingPlanoTx5"),
    _4390000006: makeNodeComponent("_4390000006"),
    acquisitionFinancing5: makeNodeComponent("acquisitionFinancing5"),
    office6: makeNodeComponent("office6"),
    screenShot20210826At12531: makeNodeComponent("screenShot20210826At12531"),
    greystoneLogo: makeNodeComponent("greystoneLogo"),
    group: makeNodeComponent("group"),
    newmarkLogoBlack: makeNodeComponent("newmarkLogoBlack"),
    symbols: makeNodeComponent("symbols"),
    moleculeHeaderPositive: makeNodeComponent("moleculeHeaderPositive"),
    pgimDark: makeNodeComponent("pgimDark"),
    symbols2: makeNodeComponent("symbols2"),
    desktopGlobalNavigationDarkPgim: makeNodeComponent(
      "desktopGlobalNavigationDarkPgim"
    ),
    navigation: makeNodeComponent("navigation"),
    siteBranding: makeNodeComponent("siteBranding"),
    assetsLogosPgimDark: makeNodeComponent("assetsLogosPgimDark"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
